# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'NexmoTest3.0.1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NexmoTest3.0.1
  pod 'NexmoClient', '3.0.1'

  target 'NexmoTest3.0.1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NexmoTest3.0.1UITests' do
    # Pods for testing
  end

end
